### ISSUE TITLE
[Feature Request] Add option to add grain to AnimatedMeshGradient

### ISSUE THREAD

**Issue by rienkkk** [ben-fornefeld/mesh_gradient#15]
Thanks for the package. It has made my app look quite a bit better already. I think adding the option to add grain to the AnimatedMeshGradient will be an awesome addition.

**Comment by rienkkk** [comment]
That was awesomely quick! ❤️ Thanks a lot!

**Comment by ben-fornefeld** [comment]
@rienkkk just implemented a basic version which gives a grainy texture in 1.3.5. i would love to get some honest feedback if this is what you imagined or can be improved further

**Comment by rienkkk** [comment]
@ben-fornefeld - I think something went wrong, when using this basic implementation:

`AnimatedMeshGradient(
                      colors: [
                        Colors.red,
                        Colors.green,
                        Colors.blue,
                        Colors.orange,
                      ],
                      options: AnimatedMeshGradientOptions(),
                      child: Container(
                        width: 100,
                        height: 100,
                      ),
                    )`

I get this error repeatedly:
RangeError (index): Index out of range: index should be less than 18: 18

Different question, and no problem if it is necessary, but just curious. Why does it exactly have to be 4 colors?

**Comment by ben-fornefeld** [comment]
i tested it on mac & ios and could not recreate. can you give me specifics on your environment?


> Different question, and no problem if it is necessary, but just curious. Why does it exactly have to be 4 colors?

A: the shader powering the gradient was made for exactly four colors and since my focus is on MeshGradient, i was never bothered to change that. you can add two of the same colors if you want to use less, that is kind of a workaround at the moment. my goal would be to get MeshGradient in much better shape that it is now, then you have more customisability with the same fluid aesthetics of AnimatedMeshGradient.

**Comment by rienkkk** [comment]
@ben-fornefeld - Sorry a mistake from my side, after restarting and cleaning the project it seems to work. I think some cache from the previous version was left.

The trick of adding the same colors, is what I am using now indeed!

**Comment by ben-fornefeld** [comment]
@rienkkk nice, feel free to give me feedback on the effect

**Comment by rienkkk** [comment]
Perfect! Exactly how I wanted it. A quick demo of how I use your package in my app:

https://github.com/ben-fornefeld/mesh_gradient/assets/57758628/cdfba864-27a0-47e5-92a7-f7198792e7de
