### ISSUE TITLE
Not working on web-mobile devices

### ISSUE THREAD

**Issue by emanoelviana** [ben-fornefeld/mesh_gradient#19]
I built a website using this package. It works perfectly on desktop web browsers, but it doesn't work on mobile browsers. For example, it works on my computer's browser, but not on my cellphone.

The website I'm trying to build is this: emanoelviana.com

I'm using the MeshGradient widget, the most basic, without animations.

**Comment by ben-fornefeld** [comment]
@emanoelviana could you provide information about your environment / flutter version?

**Comment by emanoelviana** [comment]
Sure. I'm documenting the project in a repository and I'm using the mesh_gradient package in this file: https://github.com/emanoelviana/emanoelviana.com/blob/main/lib/src/widgets/introduction/introduction.dart
the pubspec.yaml: https://github.com/emanoelviana/emanoelviana.com/blob/main/pubspec.yaml

**Comment by ben-fornefeld** [comment]
thanks, take a look at [this](https://github.com/flutter/flutter/issues/135842) issue. does switching the web renderer to `canvaskit` resolve your issue?
