### ISSUE TITLE
Running on physical without a child shows blank white and makes app irresponsive (iOS)

### ISSUE THREAD

**Issue by MaherSafadii** [ben-fornefeld/mesh_gradient#2]
if I run the gradient on a iOS simulator normally without a child it works fine but when I run it on a physical device it shows white and the app will become irresponsive and Xcode shows this error message in the console:

`-[MTLDebugRenderCommandEncoder validateCommonDrawErrors:]:5775: failed assertion `Draw Errors Validation
Fragment Function(animated_mesh_gradient_fragment_main): argument uColor4[0] from buffer(8) with offset(224) and length(236) has space for 12 bytes, but argument has a length(16).
'`

` AnimatedMeshGradient(
      colors: const [
        Color(0xFFD500FF),
        Colors.black,
        Color(0xFFEA7FFF),
        Color(0xFF352297),
      ],
      options: AnimatedMeshGradientOptions(),
    )`

this has no child and only works in the iOS simulator, but won't work on a physical device.

` AnimatedMeshGradient(
      colors: const [
        Color(0xFFD500FF),
        Colors.black,
        Color(0xFFEA7FFF),
        Color(0xFF352297),
      ],
      options: AnimatedMeshGradientOptions(),
      child: const Text("text"),
    )`

I have to add a child for the Xcode error to go and for it to work on a physical device.

**Comment by ben-fornefeld** [comment]
@MaherSafadii i am not able to reproduce this at the moment. 

can you provide more information on your environment  & maybe code examples?
