### ISSUE TITLE
Repeat animation

### ISSUE THREAD

**Issue by Fintasys** [ben-fornefeld/mesh_gradient#24]
Hey 
The plugin works great, thank you!
I was wondering if there is an easy way to repeat an animation? I'm kinda miss a `.repeat()` method on the MeshController similar to AnimationController.

Would be nice to have 🙏

**Comment by ben-fornefeld** [comment]
sure, could you tell me how you're imagining to use this inside your codebase? what would be a good dx in your opinion?

question: would there be anything different than just putting your controller call in a function and just calling it multiple times?

**Comment by Fintasys** [comment]
Ended up using `AnimatedMeshGradient` which was exactly what I was looking for. It endlessly animates. Nevertheless, I had trouble to reproduce same behavior using the controller.
Feel free to close this issue unless you want to follow up on this 🙏 Thank you
