### ISSUE TITLE
FragmentProgram is not supported in FlutterFlow

### ISSUE THREAD

**Issue by sergor5** [ben-fornefeld/mesh_gradient#4]
I tried to use this package in an FlutterFlow project.

It gives me this error in console of the Chrome browser:
`Uncaught Unsupported operation: FragmentProgram is not supported for the HTML renderer.`
![image](https://github.com/ben-fornefeld/mesh_gradient/assets/29211821/8d2d73da-bdd3-43f8-bb21-47c7274c68ee)

Just to check I've downloaded the project's source code and ran the project locally.
Both the IOS and Web seems working locally.
<img width="616" alt="image" src="https://github.com/ben-fornefeld/mesh_gradient/assets/29211821/4ece3279-f3bd-4f78-853f-a453d18f8092">
<img width="529" alt="image" src="https://github.com/ben-fornefeld/mesh_gradient/assets/29211821/4ae2678b-6061-4367-9dff-67a62510262f">

I'm not sure what can be done here kinda new in flutter development, any ideas?

Note: As for now FlutterFlow uses version `3.13.7 `of flutter. And on my local machine I have flutter `3.16.8-stable`.

**Comment by ben-fornefeld** [comment]
@sergor5 seems like fragment shaders are blocked by flutterflows renderer. not sure if i can do anything about it, since this package requires fragment shaders

**Comment by Tswan** [comment]
@ben-fornefeld I think I would like to explore this issue futher. This is an amazing package you've created, and I could definitely see the benefit of getting this running on FlutterFlow.

Do you think you could expand on the issue of the fragment shaders are blocked by flutterflows renderer? Like would you guess this would run on a published website using FlutterFlow?
